/*
 * Catálogo editorial basado en referencias públicas de Lenda (octubre de 2026).
 * IMPORTANTE: Estos importes son precios mínimos orientativos ("desde"),
 * no corresponden necesariamente al mismo peso ni representan oferta propia.
 * Antes de comercializar: añadir SKU, EAN, variantes/pesos, IVA, coste, stock,
 * política de precios y autorización para usar activos oficiales.
 */
const PRODUCTS = [
  { id: 'gf-puppy', name: 'Lenda Grain Free Puppy', subtitle: 'Una gran aventura empieza pequeña', family: 'GRAIN FREE', category: ['cachorro'], protein: 'Conejo y pescado', tags: ['Sin cereales', 'Cachorro'], priceFrom: 20.90, badge: 'Para cachorros', color: '#c8a87b', ink: '#4b3325', pack: '#e1cbaa', accent: '#8e6646', motif: '✳', url: 'https://shop.lenda.net/products/lenda-grain-free-cachorro', description: 'Receta Grain Free de la línea Puppy. Consulta ingredientes, ración y formatos en su ficha oficial.' },
  { id: 'gf-pato-pavo', name: 'Lenda Grain Free Pato y Pavo', subtitle: 'Sabor para los más exploradores', family: 'GRAIN FREE', category: ['adulto'], protein: 'Pato y pavo', tags: ['Sin cereales', 'Adulto'], priceFrom: 23.90, badge: 'Muy buscado', color: '#9fa784', ink: '#344333', pack: '#bac3a7', accent: '#546a47', motif: '◈', url: 'https://shop.lenda.net/products/lenda-grain-free-pato-y-pavo', description: 'Receta de pato y pavo de la gama Grain Free, sin cereales. Ver detalles de la formulación en Lenda.' },
  { id: 'mono-salmon', name: 'Lenda Monoproteico Salmón', subtitle: 'Una receta para descubrir', family: 'GRAIN FREE', category: ['adulto'], protein: 'Salmón', tags: ['Monoproteico', 'Sin cereales'], priceFrom: 20.90, badge: 'Monoproteico', color: '#deafa1', ink: '#6b413d', pack: '#eed0c6', accent: '#9c6056', motif: '✺', url: 'https://shop.lenda.net/search?q=grain+free+monoproteico+salmon', description: 'Variedad monoproteica de salmón. Revisa la ficha del fabricante antes de elegirla para perros con sensibilidades.' },
  { id: 'mini-meat-fish', name: 'Lenda Mini Meat & Fish', subtitle: 'Grandes cosas para perros pequeños', family: 'MINI', category: ['adulto', 'mini'], protein: 'Carnes y pescado', tags: ['Raza pequeña', 'Adulto'], priceFrom: 18.99, badge: 'Razas pequeñas', color: '#b7c1b0', ink: '#334e47', pack: '#d3ddd1', accent: '#527568', motif: '✳', url: 'https://shop.lenda.net/products/mini-meat-fish', description: 'Receta de la gama Mini, diseñada para perros de tamaño pequeño. Comprueba tamaño de croqueta y formato.' },
  { id: 'gf-mini-fish', name: 'Lenda Mini Pescado y Krill', subtitle: 'Del mar a su cuenco', family: 'GRAIN FREE MINI', category: ['adulto', 'mini'], protein: 'Pescado y krill', tags: ['Sin cereales', 'Raza pequeña'], priceFrom: 23.90, badge: 'Para minis', color: '#9ab5b0', ink: '#244a53', pack: '#bbd3d1', accent: '#416d75', motif: '✳', url: 'https://shop.lenda.net/products/lenda-grain-free-mini-pescado-y-krill', description: 'Pienso Grain Free Mini de pescado y krill. Información técnica disponible en la ficha oficial.' },
  { id: 'gf-senior', name: 'Lenda Light & Senior', subtitle: 'A su lado en cada etapa', family: 'GRAIN FREE', category: ['senior', 'adulto'], protein: 'Conejo y pavo', tags: ['Senior', 'Control de peso'], priceFrom: 20.90, badge: 'Senior', color: '#b5b6cb', ink: '#3c3e5a', pack: '#d3d2e0', accent: '#72738e', motif: '✺', url: 'https://shop.lenda.net/products/lenda-grain-free-light-y-senior', description: 'Línea Light & Senior pensada para otras necesidades de la etapa adulta. Consulta la receta y orientación de uso.' },
  { id: 'mini-first', name: 'Lenda Mini Puppy First Bites', subtitle: 'Pequeños bocados, grandes comienzos', family: 'MINI PUPPY', category: ['cachorro', 'mini'], protein: 'Pollo y pavo', tags: ['Cachorro', 'Raza pequeña'], priceFrom: 18.99, badge: 'Primeros bocados', color: '#e4bb88', ink: '#5d4228', pack: '#f3d7af', accent: '#ad7848', motif: '◈', url: 'https://shop.lenda.net/products/lenda-puppy-mini-first-bite', description: 'Variedad Lenda Mini para cachorros de tamaño pequeño. Revisa peso, edad y raciones recomendadas por Lenda.' },
  { id: 'urban-pollo', name: 'Lenda Urban Farm Flavour Pollo', subtitle: 'Un clásico para el día a día', family: 'URBAN', category: ['adulto'], protein: 'Pollo', tags: ['Adulto', 'Urban'], priceFrom: 12.90, badge: 'Urban', color: '#c8bf94', ink: '#57503a', pack: '#e4dcba', accent: '#8b7d4b', motif: '✳', url: 'https://shop.lenda.net/products/urban-flavour-chicken', description: 'Variedad Urban de sabor pollo. Revisa la formulación y los diferentes tamaños de saco.' }
];
const CATEGORIES = [
 {id:'todos', label:'Todos'}, {id:'cachorro',label:'Cachorros'}, {id:'adulto',label:'Adultos'}, {id:'mini',label:'Raza pequeña'}, {id:'senior',label:'Senior'}
];
